/**
 * VPIC1 — I18n dictionary data
 * -----------------------------------------------------------------------
 * Pure data: no logic here. This file only holds the supported languages
 * and the vi/en/zh string tables. Runtime logic (t, setLang, applyI8n...)
 * lives in ./i8n.ts.
 */

export type Lang = "vi" | "en" | "zh";

export type Dict = Record<string, string>;

export const SUPPORTED: Lang[] = ["vi", "en", "zh"];

export const DICT: Record<Lang, Dict> = {
  vi: {
    "tagline": "",

    "s1.title": "Tệp đầu vào",
    "s1.choose": "Chọn tệp STEP / STL / 3MF…",
    "s1.none": "Chưa tải tệp nào",

    "info.title": "Thông tin tệp",
    "info.cad": "Phần mềm CAD",
    "info.schema": "Schema",
    "info.units": "Đơn vị",
    "info.dims": "Kích thước",
    "info.bodies": "Số khối",
    "info.faces": "Số mặt",
    "info.tris": "Tam giác",
    "info.openEdges": "Cạnh hở",
    "info.exported": "Ngày xuất",
    "info.watertight": "Kín nước",
    "info.notWatertight": "Không kín nước",

    "s2.title": "Chuyển sang lưới (mesh)",
    "s2.convert": "Chuyển đổi",
    "s2.export": "Xuất STL…",
    "s2.refine": "Thiết lập độ chi tiết",
    "s2.surfDev": "Độ lệch bề mặt",
    "s2.normDev": "Độ lệch pháp tuyến",
    "s2.maxEdge": "Chiều dài cạnh tối đa",

    "s3.title": "Hiển thị",
    "s3.shaded": "Bóng khối",
    "s3.transparent": "Trong suốt",
    "s3.wireframe": "Khung dây",
    "s3.edges": "Chỉ cạnh",
    "s3.smooth": "Đổ bóng mượt",
    "s3.crease": "Ngưỡng góc gấp nếp",
    "s3.colors": "Màu mô hình (từ STEP)",
    "s3.boundaries": "Đường biên mặt (CAD)",
    "s3.highlightOpen": "Làm nổi cạnh hở",

    "parts.title": "Danh sách chi tiết",
    "parts.hint": "Rê chuột để làm nổi · bỏ chọn để ẩn",
    "parts.showAll": "Hiện tất cả",
    "parts.hideAll": "Ẩn tất cả",

    "s4.title": "STL tham chiếu & độ lệch",
    "s4.choose": "Chọn STL tham chiếu…",
    "s4.none": "Chưa có tệp tham chiếu",
    "s4.overlay": "Chồng lớp tham chiếu",
    "s4.colorDev": "Tô màu theo độ lệch",
    "s4.range": "Dải màu ±",
    "s4.auto": "tự động",

    "vp.controls": "Điều khiển",
    "vp.hint": "kéo để xoay · cuộn để phóng to · kéo phải để di chuyển · chuột phải để mở menu chi tiết",
    "vp.fit": "Vừa khung",
    "vp.views": "Góc nhìn ▾",
    "vp.iso": "Đẳng trắc",
    "vp.top": "Trên",
    "vp.bottom": "Dưới",
    "vp.front": "Trước",
    "vp.back": "Sau",
    "vp.left": "Trái",
    "vp.right": "Phải",
    "vp.ortho": "Song song",
    "vp.perspective": "Phối cảnh",
    "vp.section": "Cắt lát",
    "vp.measure": "Đo",
    "vp.explode": "Nổ lắp",
    "vp.flip": "Lật",
    "vp.dist": "Khoảng cách",
    "vp.edge": "Cạnh",
    "vp.clear": "Xóa",
    "vp.hierarchical": "Theo nhóm",
    "vp.radial": "Tỏa tròn",
    "vp.axis": "Xếp trục",
    "vp.peel": "Bóc lớp",
    "vp.layout": "Trải phẳng",
    "vp.auto": "Tự động",
    "vp.collapse": "Thu gọn",

    "overlay.working": "Đang xử lý…",
    "status.loaded": "Đã tải {name}",
    "status.converting": "Đang chuyển đổi…",
    "status.done": "Hoàn tất",
    "status.error": "Lỗi: {msg}"
  },

  en: {
    "tagline": "",

    "s1.title": "Input",
    "s1.choose": "Choose STEP / STL / 3MF file…",
    "s1.none": "No file loaded",

    "info.title": "File info",
    "info.cad": "CAD program",
    "info.schema": "Schema",
    "info.units": "Units",
    "info.dims": "Dimensions",
    "info.bodies": "Bodies",
    "info.faces": "Faces",
    "info.tris": "Triangles",
    "info.openEdges": "Open edges",
    "info.exported": "Exported",
    "info.watertight": "Watertight",
    "info.notWatertight": "Not watertight",

    "s2.title": "Convert to mesh",
    "s2.convert": "Convert",
    "s2.export": "Export STL…",
    "s2.refine": "Refinement settings",
    "s2.surfDev": "Surface deviation",
    "s2.normDev": "Normal deviation",
    "s2.maxEdge": "Max edge length",

    "s3.title": "Appearance",
    "s3.shaded": "Shaded",
    "s3.transparent": "Transparent",
    "s3.wireframe": "Wireframe",
    "s3.edges": "Edges",
    "s3.smooth": "Smooth shading",
    "s3.crease": "Crease angle threshold",
    "s3.colors": "Model colors (from STEP)",
    "s3.boundaries": "Surface boundaries (CAD faces)",
    "s3.highlightOpen": "Highlight open edges",

    "parts.title": "Parts",
    "parts.hint": "Hover to highlight · uncheck to hide",
    "parts.showAll": "Show all",
    "parts.hideAll": "Hide all",

    "s4.title": "Reference STL & deviation",
    "s4.choose": "Choose reference STL…",
    "s4.none": "No reference",
    "s4.overlay": "Overlay reference",
    "s4.colorDev": "Color by deviation",
    "s4.range": "Color range ±",
    "s4.auto": "auto",

    "vp.controls": "Controls",
    "vp.hint": "drag to orbit · scroll to zoom · right-drag to pan · right-click for part menu",
    "vp.fit": "Fit",
    "vp.views": "Views ▾",
    "vp.iso": "Isometric",
    "vp.top": "Top",
    "vp.bottom": "Bottom",
    "vp.front": "Front",
    "vp.back": "Back",
    "vp.left": "Left",
    "vp.right": "Right",
    "vp.ortho": "Ortho",
    "vp.perspective": "Perspective",
    "vp.section": "Section",
    "vp.measure": "Measure",
    "vp.explode": "Explode",
    "vp.flip": "Flip",
    "vp.dist": "Distance",
    "vp.edge": "Edge",
    "vp.clear": "Clear",
    "vp.hierarchical": "Grouped",
    "vp.radial": "Radial",
    "vp.axis": "Stacked",
    "vp.peel": "Peel",
    "vp.layout": "Flat lay",
    "vp.auto": "Auto",
    "vp.collapse": "Collapse",

    "overlay.working": "Working…",
    "status.loaded": "Loaded {name}",
    "status.converting": "Converting…",
    "status.done": "Done",
    "status.error": "Error: {msg}"
  },

zh: {
    "tagline": "",

    "s1.title": "輸入文件",
    "s1.choose": "選擇 STEP / STL / 3MF 文件…",
    "s1.none": "尚未加載文件",

    "info.title": "文件信息",
    "info.cad": "CAD 軟體",
    "info.schema": "架構 (Schema)",
    "info.units": "單位",
    "info.dims": "尺寸",
    "info.bodies": "實體數",
    "info.faces": "面數",
    "info.tris": "三角面數",
    "info.openEdges": "開放邊",
    "info.exported": "導出日期",
    "info.watertight": "水密",
    "info.notWatertight": "非水密",

    "s2.title": "轉換為網格",
    "s2.convert": "轉換",
    "s2.export": "導出 STL…",
    "s2.refine": "細化設置",
    "s2.surfDev": "表面偏差",
    "s2.normDev": "法線偏差",
    "s2.maxEdge": "最大邊長",

    "s3.title": "外觀",
    "s3.shaded": "著色",
    "s3.transparent": "透明",
    "s3.wireframe": "線框",
    "s3.edges": "僅邊線",
    "s3.smooth": "平滑著色",
    "s3.crease": "折痕角度閾值",
    "s3.colors": "模型顏色（來自 STEP）",
    "s3.boundaries": "表面邊界（CAD 面）",
    "s3.highlightOpen": "高亮開放邊",

    "parts.title": "零件",
    "parts.hint": "懸停高亮 · 取消勾選可隱藏",
    "parts.showAll": "全部顯示",
    "parts.hideAll": "全部隱藏",

    "s4.title": "參考 STL 與偏差",
    "s4.choose": "選擇參考 STL…",
    "s4.none": "無參考文件",
    "s4.overlay": "疊加參考模型",
    "s4.colorDev": "按偏差著色",
    "s4.range": "顏色範圍 ±",
    "s4.auto": "自動",

    "vp.controls": "操作方式",
    "vp.hint": "拖動旋轉 · 滾動縮放 · 右鍵拖動平移 · 右鍵單擊打開零件菜單",
    "vp.fit": "適應窗口",
    "vp.views": "視圖 ▾",
    "vp.iso": "等軸測",
    "vp.top": "頂視圖",
    "vp.bottom": "底視圖",
    "vp.front": "前視圖",
    "vp.back": "後視圖",
    "vp.left": "左視圖",
    "vp.right": "右視圖",
    "vp.ortho": "正交",
    "vp.perspective": "透視",
    "vp.section": "剖切",
    "vp.measure": "測量",
    "vp.explode": "爆炸視圖",
    "vp.flip": "翻轉",
    "vp.dist": "距離",
    "vp.edge": "邊",
    "vp.clear": "清除",
    "vp.hierarchical": "分組",
    "vp.radial": "放射狀",
    "vp.axis": "堆疊",
    "vp.peel": "剝離",
    "vp.layout": "平鋪",
    "vp.auto": "自動",
    "vp.collapse": "收攏",

    "overlay.working": "處理中…",
    "status.loaded": "已加載 {name}",
    "status.converting": "正在轉換…",
    "status.done": "完成",
    "status.error": "錯誤：{msg}"
}
};